### ISSUE TITLE
Difference Postponed/Pending

### ISSUE THREAD

**Issue by ilvalerione** [hootlex/laravel-moderation#25]
Hello Hotlex, thanks for this package, I'm interesting to adopt it in my project.

I have not a lot of experience in content moderation so can you give more details about difference from Postponed and Pending status? It seams a redundant definition.

Really thanks
Valerio

**Comment by hootlex** [comment]
Hey,

Pending is the default status. After that, the moderator can choose to approve, reject, or postpone the resource.

This is useful for situations where you show to a moderator all pending resources and some of them might be someone else's responsibility or he might just be unsure if he should approve them. So, in order to exclude these from pending you mark them as postponed.
