### ISSUE TITLE
Actions on a single instance

### ISSUE THREAD

**Issue by sebastiaanluca** [hootlex/laravel-moderation#6]
Perhaps an idea to allow `$user->approve()`, `$user->reject`, `$user->postpone()`, et cetera? :)

Oh, and scopes! That way it can be combined with other query limitations like wheres and whatnot.

**Comment by hootlex** [comment]
With `$user->approve()` you mean `$user->approve($resource)`?

And what about scopes? It works with scopes already.

**Comment by sebastiaanluca** [comment]
@hootlex I mean `$user` is the moderated resource and I want to approve, reject, postpone it. E.g. `$post->reject()` instead of doing `Post::reject($postId)`. So on the instance itself, should've made that  clear in the first post.

**Comment by hootlex** [comment]
I like this feature too. Before I published this package I tried to implement these methods but there were collisions with `approve`, `reject`, ... function between the trait and the scope, since both had the same names. So, I had 2 options: 1. Rename functions on the trait (ex. doApprove) 2. Remove the functions.

As you can see I chose the second option since I didnt like to have both `approve` and `doApprove` functions. :)

If you believe that it will be useful to call `$user->doApprove()`, or if you have an idea on how it can be achieved to share the same method names let me know.

**Comment by furqan99** [comment]
how to delete the rejected post ?

**Comment by hootlex** [comment]
You can delete it directly using `$post->delete()` or use `withRejected` scope inside a query.

**Comment by furqan99** [comment]
it give me error  using $post->delete ()
NotFoundHttpException in Handler.php line 102:
No query results for model [App\Post].

**Comment by hootlex** [comment]
Which laravel version do you use?

**Comment by furqan99** [comment]
i am use 5.2

**Comment by hootlex** [comment]
Does the scope work for you?

**Comment by furqan99** [comment]
yes its work  but rejected and unapproved post do not delete give me error .

**Comment by hootlex** [comment]
I tested it myself and I am able to delete rejected/pending posts running

```php
$post = Post::withRejected()->where('id', $id)->first();
$post->delete();
```

Please update the package to the latest version.

**Comment by furqan99** [comment]
Thank you (y)

**Comment by hootlex** [comment]
Did the update fix your issue?

**Comment by yoongkang0122** [comment]
@hootlex  you are great man!!! i love your book. I hope you can publish more book. Then can continue to learn new thing with you

**Comment by hootlex** [comment]
@yoongkang0122 thanks your kind words, I am glad you like it. 
For issues regarding the book please head to this [repo](https://github.com/hootlex/the-majesty-of-vuejs).

**Comment by hootlex** [comment]
@sebastiaanluca methonds on single instace have been added on v1.0.6.
